# FEATURE ENGINEERING
From the exploratory data analysis stage, we have made observations about the dataset that necessitate feature engineering so that we can reduce dimensionality

We will do the following:
- Drop the 'sysBP' and 'diaBP' since they are so correlated, and replace with mean arterial pressure (MAP)
- Drop the education and prevalent stroke columns since they are redundant

In [38]:
# Import libraries
import pandas as pd
import numpy as np

In [39]:
# Read in raw data
df = pd.read_csv('../data/framingham.csv')

In [41]:
# Creating mean arterial pressure column
df['MAP'] = df.apply(
    lambda row: row['diaBP'] + (1/3) * (row['sysBP'] - row['diaBP']),
    axis = 1)

# Dropping 'sysBP' and 'diaBP'
df = df.drop(columns=['sysBP', 'diaBP'])
df.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,totChol,BMI,heartRate,TenYearCHD,diabetesGrade,MAP
0,1,39,4.0,0,0.0,0.0,0,0,195.0,26.97,80.0,0,2,82.000000
1,0,46,2.0,0,0.0,0.0,0,0,250.0,28.73,95.0,0,2,94.333333
2,1,48,1.0,1,20.0,0.0,0,0,245.0,25.34,75.0,0,1,95.833333
3,0,61,3.0,1,30.0,0.0,0,1,225.0,28.58,65.0,1,3,113.333333
4,0,46,3.0,1,23.0,0.0,0,0,285.0,23.10,85.0,0,2,99.333333

In [42]:
# Drop columns that were found to add negligible value
df.drop(columns=['education','prevalentStroke'])

,male,age,currentSmoker,cigsPerDay,BPMeds,prevalentHyp,totChol,BMI,heartRate,TenYearCHD,diabetesGrade,MAP
0,1,39,0,0.0,0.0,0,195.0,26.97,80.0,0,2,82.000000
1,0,46,0,0.0,0.0,0,250.0,28.73,95.0,0,2,94.333333
2,1,48,1,20.0,0.0,0,245.0,25.34,75.0,0,1,95.833333
3,0,61,1,30.0,0.0,1,225.0,28.58,65.0,1,3,113.333333
4,0,46,1,23.0,0.0,0,285.0,23.10,85.0,0,2,99.333333
...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,48,1,20.0,NaN,0,248.0,22.00,84.0,0,2,91.666667
4236,0,44,1,15.0,0.0,0,210.0,19.16,86.0,0,1,100.166667
4237,0,52,0,0.0,0.0,0,269.0,21.47,80.0,0,3,99.833333
4238,1,40,0,0.0,0.0,1,185.0,25.60,67.0,0,2,112.333333
4239,0,39,1,30.0,0.0,0,196.0,20.91,85.0,0,2,101.666667